### ISSUE TITLE
Value of type 'Response' has no member 'mapArray'

### ISSUE THREAD

**Issue by AsimNet** [ivanbruel/Moya-ObjectMapper#14] opened 2016-06-19 15:27 UTC
Hello,

when I tried to use the code in the example 
`            if let repos = try response.mapArray(Repository) {
`
it gives me this message 

> Value of type 'Response' has no member 'mapArray'

thanks,

**Comment by tianxiewuhua** [comment] 2016-06-27 08:02
you should write "import Moya_ObjectMapper" in the header of your swift file

**Comment by ivanbruel** [comment] 2016-06-28 15:04
This should be fixed on version `1.3`, let me know if this comes up again.

**Closed by ivanbruel** 2016-06-28 15:04 UTC

**Comment by rodolfohelfenstein** [comment] 2016-12-29 17:22
I'm still with this problem.

**Comment by patrikqvarnstrom** [comment] 2017-04-11 10:50
Having this same issue

**Comment by dfabreguette-ap** [comment] 2017-07-25 09:31
I also have the same issue. any idea ? 
The issue is a duplicate to https://github.com/ivanbruel/Moya-ObjectMapper/issues/32.
I tried importing manually the "Observable+ObjectMapper.swift" file but it changed nothing.

Here's my Podfile :
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile
  pod 'NVActivityIndicatorView'
  pod 'Alamofire', '~> 4.4'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'Moya'
  pod 'RxSwift'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by jjercTK** [comment] 2017-07-25 20:31
Hi, I think it's something related to `Moya-ObjectMapper/RxSwift `

My old Podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook
  pod 'Moya'
  pod 'RxSwift'
  pod 'Moya-ModelMapper', '4.0.0'
  pod 'Moya-ModelMapper/RxSwift', '4.0.0'
  pod 'SDWebImage'
  pod 'SwiftyBeaver'
end
```

My new Podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook
  pod 'Moya'
  pod 'RxSwift'
  pod 'Moya-ModelMapper', '4.0.0'
  pod 'SDWebImage'
  pod 'SwiftyBeaver'
end
```

**Comment by ptrocki** [comment] 2017-08-17 08:31
In swift file use` import Moya_ObjectMapper`

**Comment by whiteholekong** [comment] 2017-09-18 02:14
I also have this problem after updated to Moya-ObjectMapper (2.4).
I cannot compile my project and my apps cannot run again! :-(
